export {default as Navbar} from './navbar/Navbar'
export {default as About} from './about/About'
export {default as Projects} from './projects/Projects'
export {default as Work} from './work/Work'
export {default as Skills} from './skills/Skills'
